# Generated by Django 4.2.7 on 2025-07-02 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Salário', 'Salário'), ('Freelance', 'Freelance'), ('Investimento', 'Investimento'), ('Venda', 'Venda'), ('Parcelado', 'Parcelado'), ('Outros', 'Outros')], max_length=50)),
                ('responsavel', models.CharField(choices=[('Pessoa 1', 'Pessoa 1'), ('Pessoa 2', 'Pessoa 2'), ('Ambos', 'Ambos')], max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('data', models.DateField()),
                ('parcelas', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('parcela_atual', models.PositiveIntegerField(default=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
