# Generated by Django 4.2.7 on 2025-07-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ['-data'], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
        migrations.RenameField(
            model_name='gasto',
            old_name='data_criacao',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='gasto',
            old_name='data_atualizacao',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('Alimentacao', 'Alimentação'), ('Transporte', 'Transporte'), ('Moradia', 'Moradia'), ('Saude', 'Saúde'), ('Educacao', 'Educação'), ('Lazer', 'Lazer'), ('Vestuario', 'Vestuário'), ('Outros', 'Outros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='parcela_atual',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='parcelas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Vencido', 'Vencido')], default='Pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='tipo',
            field=models.CharField(choices=[('Unico', 'Único'), ('Parcelado', 'Parcelado'), ('Recorrente', 'Recorrente')], default='Unico', max_length=20),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
